services:
  pathfinder2:
    image: jaensen/pathfinder2:server-only
    restart: unless-stopped
    network_mode: host
    volumes:
      - .state/pathfinder-db:/pathfinder-db
  
  pathfinder2-updater:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - .state/pathfinder-db:/pathfinder-db